Update configuration tools to their latest version. Use DevOps tools from https://gite.lirmm.fr/doccy-dev-tools/. Update copyright notices. Fix bugs on archive distribution and package release. Fix bugs when built from a dediczted subdirectory. Fix doxygen/pdf error due to the σ UTF-8 symbol in the ChangeLog (yes, now it works but please, BilbOK, never ever do that again !!!).

diff --git a/config/git-version-gen b/config/git-version-gen
--- a/config/git-version-gen
+++ b/config/git-version-gen
@@ -1,7 +1,7 @@
 #!/bin/bash
 ###############################################################################
 #                                                                             #
-#  Copyright © 2016-2023 -- LIRMM/CNRS/UM                                     #
+#  Copyright © 2016-2025 -- LIRMM/CNRS/UM                                     #
 #                           (Laboratoire d'Informatique, de Robotique et de   #
 #                           Microélectronique de Montpellier /                #
 #                           Centre National de la Recherche Scientifique /    #
@@ -11,7 +11,8 @@
 #                                                                             #
 #  -------------------------------------------------------------------------  #
 #                                                                             #
-#  Ce logiciel permet de gérer le versionnage sémantique d'un fichier.        #
+#  Ce logiciel permet  de gérer le marquage  des versions logicielles et des  #
+#  éventuelles librairies versionnées dans un dépôt git.                      #
 #                                                                             #
 #  Ce logiciel est régi  par la licence CeCILL  soumise au droit français et  #
 #  respectant les principes  de diffusion des logiciels libres.  Vous pouvez  #
@@ -42,7 +43,8 @@
 #                                                                             #
 #  -------------------------------------------------------------------------  #
 #                                                                             #
-#  This software allows to manage the semantic versioning of some file.       #
+#  This software allow to manage tags for distribute software and library     #
+#  releases inside a git repository.                                          #
 #                                                                             #
 #  This software is governed by the CeCILL license under French law and       #
 #  abiding by the rules of distribution of free software. You can use,        #
@@ -71,52 +73,60 @@
 #  knowledge of the CeCILL license and that you accept its terms.             #
 #                                                                             #
 ###############################################################################
-DIRNAME=$(dirname "$(readlink -m "$0")")
+
+set -e
+
+DIRNAME=$(dirname "$(readlink -m -- "$0")")
 PROG_NAME=$(basename "$0")
-PROG_DIR=$(dirname "$(readlink -m "$0")")
-MAIN_DIR=$(dirname "$PROG_DIR")
+PROG_DIR=$(dirname "$(readlink -m -- "$0")")
 PROJECT_VERSION_FILE="version"
 VERSION_FILE_PREFIX="version."
-STORE="[project root]/$(basename "$DIRNAME")"
+STORE=
+DEFAULT_STORE="$(basename "${DIRNAME}")"
 TIMESTAMP=false
 FORCE_UPDATE=auto
 CREATE_FILE=auto
+FILE=
+GIT="$(which git)"
+NO_VERSION="[unknown]"
+NO_COMMIT_DATE="(unknown)"
 
-if [ $# -ge 1 -a "$1" = "--timestamp" ]; then
-    TIMESTAMP=true
-    shift
-fi
-if [ $# -ge 1 -a "$1" = "--force-update" ]; then
-    FORCE_UPDATE=true
-    shift
-fi
-if [ $# -ge 1 -a "$1" = "--no-create" ]; then
-    CREATE_FILE=false
-    shift
-fi
-if [ $# -ge 1 -a "$1" = "--force-creation" ]; then
-    CREATE_FILE=true
-    shift
-fi
-if [ $# -eq 1 -a "$1" != "--help" -a "$1" != "-h" ]; then
-    [ "$1" != "--" ] && FILE="$1"
-    shift
-fi
-if [ $# -gt 0 -a -z "$FILE" ]; then
-    cat<<EOF
+function usage {
+  cat<<EOF
 
-usage: $(basename $0) [--timestamp] [--force-update] [--no-create|--force-creation] [<filename>]
+usage: $(basename $0) [options] [--] [<filename>]
        $(basename $0) -h|--help
 
-This script retrieve version informations of file/project.
+where options are:
+  --timestamp         Appends the last commit timestamp next to the version
+                      number.
+  --force-update      Try to read the version information from the git
+                      history (see comments below).
+  --no-create         Do not create target file.
+  --force-creation    Force target file creation (without asking any
+                      question). 
+  --store <path>      Set the directory where the version target files are
+                      stored (default: [project root]/${DEFAULT_STORE}).
+                      A relative <path> is considered from the project root.
+                      Unless --no-create option is given, the path is created
+                      if it doesn't already exist.
+  --infos <filename>  Force using <name> as information file (automatically
+                      computed by default)
+  --                  Any argument given after will be considered as a file.
+  --help | -h         Display this message.
+  --version | -v      Display ${PROG_NAME} version then exit.
 
-If no file name is given, the version information corresponds to the current
-project and the target file where informations are stored is
-"$STORE/$PROJECT_VERSION_FILE".
+This script retrieve version informations of files/project.
 
-If some file name is given, then the version information corresponds to the
-given file in the project and the target file becomes
-"$STORE/$VERSION_FILE_PREFIX<normalized-filename>".
+If no input file name is given, the version information corresponds to the
+current project and by default, the target file where informations are stored
+is:
+  "[project root]/${DEFAULT_STORE}/${PROJECT_VERSION_FILE}"
+
+If some input file name is given, then the version information corresponds
+to the given files in the project and for each, by default, the corresponding
+target file becomes:
+  "[project root]/${DEFAULT_STORE}/${VERSION_FILE_PREFIX}<normalized-filename>"
 
 If the target file exists and the '--force-update' option is not provided,
 the version information is read from the target file.
@@ -128,30 +138,142 @@ If the target file doesn't exist or if the version information has been
 updated (option '--force-update'), the target file is created unless option
 '--no-create' is provided.
 
-If the '--force-creation' option is provided, file rewriting is forced.
+EOF
+  res=0;
+  if [ -n "${1}" ]; then
+    echo "# Error: ${1} #" | sed 'h;s/./#/g;p;x;p;x'
+    echo
+    res=1
+  fi
 
-The '--timestamp' option simply appends the last commit timestamp next to the
-version number.
+  [ -n "${2}" ] || exit ${res}
+
+}
+
+# Display version + copyrights
+function version() {
+  cat<<EOF
+
+${PROG_NAME} ${PROG_VERSION} (git id: ${PROG_GITID})
+
+Copyright © 2016-2025 -- LIRMM/CNRS/UM
+                         (Laboratoire d'Informatique, de Robotique et de
+                         Microélectronique de Montpellier /
+                         Centre National de la Recherche Scientifique /
+                         Université de Montpellier)
+
+Auteur/Author: Alban MANCHERON  <alban.mancheron@lirmm.fr>
 
 EOF
-exit 0
+  #' For Xemacs
+}
+
+# Try to extract the value of the given key (first arg) in the version file.
+# Echo the value if key is found (and parseable) or the default value
+# (second arg or 0 if missing)
+function getFileConfig() {
+  [ $# = 1 ] && default=0 || default=$2
+  val=$default
+  if [ -f "${VERSION_FILE}" ]; then
+    val=$(grep "^[ ]*$1[ ]*:" "${VERSION_FILE}" | sed 's,^[ ]*'$1'[ ]*:[ ]*,,')
+    [ -z "$val" ] && val=$default
+  fi
+  echo $val
+}
+
+
+pushd  "${PROG_DIR}" > /dev/null
+if [ -f "infos/version.${PROG_NAME}" ]; then
+  VERSION_FILE="infos/version.${PROG_NAME}"
+  PROG_GITID=$(getFileConfig "VERSION" "${NO_VERSION}")
+  if [ -f "infos/version" ]; then
+    VERSION_FILE="infos/version"
+    PROG_VERSION=$(getFileConfig "VERSION" "${NO_VERSION}")
+  fi
+  VERSION_FILE=
+fi
+popd > /dev/null
+
+
+###############################################################################
+# Processing command line arguments                                           #
+###############################################################################
+while [ ${#} -ge 1 ]; do
+  case "${1}" in
+    --timestamp) TIMESTAMP=true;;
+    --force-update) FORCE_UPDATE=true;;
+    --no-create) CREATE_FILE=false;;
+    --force-creation) CREATE_FILE=true;;
+    --store) shift
+             [ ${#} -ge 1 ] || usage "Option '--store' requires an argument."
+             STORE="${1}";;
+    --infos) shift
+             [ ${#} -ge 1 ] || usage "Option '--infos' requires an argument."
+             VERSION_FILE="${1}";;
+    --help|-h) usage;;
+    --version|-v) version; exit 0;;
+    --) shift; break;;
+    -*) usage "Unknown option '${1}'.";;
+    *) [ -z "${FILE}" ] \
+         && FILE="${1}" \
+         || usage "You can't provide more than one filename.\nYou already provide '${FILE}' and now you give '${1}'";;
+  esac
+  shift
+done
+
+while [ ${#} -ge 1 ]; do
+  [ -z "${FILE}" ] \
+    && FILE="${1}" \
+      || usage "You can't provide more than one filename.\nYou already provide '${FILE}' and now you give '${1}'"
+  shift
+done
+
+###############################################################################
+# Getting the top level directory of the git project corresponding to the     #
+# current working directory.                                                  #
+###############################################################################
+MAIN_DIR=$(${GIT} rev-parse --show-toplevel 2>/dev/null || true)
+if [ -z "${MAIN_DIR}" -o ! -d "${MAIN_DIR}" ]; then
+  usage "Main git project path not found. Using current working directory [${PWD}]." no_exit >&2
+  MAIN_DIR="${PWD}"
 fi
 
-cd "$MAIN_DIR"
+###############################################################################
+# Set the target file destination directory                                   #
+###############################################################################
 
-if [ -n "$FILE" ]; then
-    VERSION_FILE=$(readlink -m "$FILE")
-    VERSION_FILE="${VERSION_FILE#"$(dirname "$DIRNAME")"/}"
-    VERSION_FILE="$(echo "$VERSION_FILE_PREFIX$VERSION_FILE" | tr / .)"
-else
-    VERSION_FILE="$PROJECT_VERSION_FILE"
+test -n "${STORE}" || STORE="${DEFAULT_STORE}"
+
+if [ "${STORE:0:1}" != "/" ]; then
+  STORE="${MAIN_DIR}/${STORE}"
 fi
 
-VERSION_FILE="$DIRNAME/$VERSION_FILE"
+if [ ! -d "${STORE}" -a "${CREATE_FILE}" != "false" ]; then
+  if [ "${CREATE_FILE}" != "true" ]; then
+    echo "Directory '${STORE}' doesn't exist. Do you wan't to create it [y/N]"
+    read rep
+  else
+    rep=y;
+  fi
+  if [ "${rep}" = "y" -o "${rep}" = "Y" ]; then
+    mkdir -p "${STORE}"
+  else
+    echo "Aborting..."
+    exit 1
+  fi
+fi
 
-NO_VERSION="[unknown]"
-NO_COMMIT_DATE="(unknown)"
-GIT="$(which git)"
+if [ -z "${VERSION_FILE}" ]; then
+  if [ -n "${FILE}" ]; then
+    VERSION_FILE=$(readlink -m -- "${FILE}")
+    VERSION_FILE="${VERSION_FILE#${MAIN_DIR}/}"
+    VERSION_FILE="$(echo "${VERSION_FILE_PREFIX}${VERSION_FILE}" | tr / .)"
+  else
+    VERSION_FILE="${PROJECT_VERSION_FILE}"
+  fi
+fi
+
+VERSION_FILE="${STORE}/${VERSION_FILE}"
 
 ## The following code is adapted from
 ## http://git.kernel.org/cgit/git/git.git/tree/GIT-VERSION-GEN?id=HEAD
@@ -159,106 +281,94 @@ FLAG=""
 FLAG_DIRTY_VALUE="-dirty"
 COMMIT_DATE=""
 COMMIT_DATE_FORMAT="%ci"
-VN="$NO_VERSION"
+VN="${NO_VERSION}"
 
 
-# Try to extract the value of the given key (first arg) in the version file.
-# Echo the value if key is found (and parseable) or the default value
-# (second arg or 0 if missing)
-function getFileConfig() {
-    [ $# = 1 ] && default=0 || default=$2
-    val=$default
-    if [ -f "$VERSION_FILE" ]; then
-	val=$(grep "^[ ]*$1[ ]*:" "$VERSION_FILE" | sed 's,^[ ]*'$1'[ ]*:[ ]*,,')
-	[ -z "$val" ] && val=$default
-    fi
-    echo $val
-}
-
-# First see if there is a file named "$VERSION_FILE" (included in release tarballs),
+# First see if there is a file named "${VERSION_FILE}" (included in release tarballs),
 # then try git commands.
-[ "$FORCE_UPDATE" = "auto"  -a -f "$VERSION_FILE" ] && FORCE_UPDATE=false
+[ "${FORCE_UPDATE}" = "auto"  -a -f "${VERSION_FILE}" ] && FORCE_UPDATE=false
 
+[ -z "${MAIN_DIR}" -a -f "${VERSION_FILE}" ] && FORCE_UPDATE=false
 
-if [ "$FORCE_UPDATE" = "true" -o ! -f "$VERSION_FILE" ]; then
-    [ "$CREATE_FILE" = "auto" ] && CREATE_FILE=true
-    if [ -d "${GIT_DIR:-.git}" -o -f .git ]; then
-	if [ -z "$GIT" ]; then
-	    echo "Warning: command 'git' not found." >&2
-	else
-	    if [ -n "$FILE" ]; then
-		$GIT update-index -q --refresh
-		if [ -e "$FILE" ]; then
-		    VN=$($GIT log --max-count=1 --pretty="%h" HEAD -- "$FILE")
-		    COMMIT_DATE=$($GIT log --max-count=1 --pretty="$COMMIT_DATE_FORMAT" HEAD -- "$FILE")
-		    [ -z "$(git diff-index --name-only HEAD -- "$FILE")" ] || FLAG="$FLAG_DIRTY_VALUE"
-		else
-		    echo "Warning: file '$FILE' not found." >&2
-		fi
-	    else
-		VN="$($GIT describe --tags --always)"
-		COMMIT_DATE=$($GIT log --max-count=1 --pretty="$COMMIT_DATE_FORMAT" HEAD)
-		[ -z "$(git diff-index --name-only HEAD)" ] || FLAG="$FLAG_DIRTY_VALUE"
-	    fi
-	fi
+if [ "${FORCE_UPDATE}" = "true" -o ! -f "${VERSION_FILE}" ]; then
+  [ "${CREATE_FILE}" = "auto" ] && CREATE_FILE=true
+  if [ -d "${MAIN_DIR:-${GIT_DIR}}" -o -f .git ]; then
+    if [ -z "${GIT}" ]; then
+      echo "Warning: command 'git' not found." >&2
     else
-	echo "Warning: git repository not found in current directory (see GIT_DIR in git documentation)." >&2
+      if [ -n "${FILE}" ]; then
+	${GIT} update-index -q --refresh
+	if [ -e "${FILE}" ]; then
+	  VN=$(${GIT} log --max-count=1 --pretty="%h" HEAD -- "${FILE}")
+	  COMMIT_DATE=$(${GIT} log --max-count=1 --pretty="${COMMIT_DATE_FORMAT}" HEAD -- "${FILE}")
+	  [ -z "$(git diff-index --name-only HEAD -- "${FILE}")" ] || FLAG="${FLAG_DIRTY_VALUE}"
+	else
+	  echo "Warning: file '${FILE}' not found." >&2
+	fi
+      else
+	VN="$(${GIT} describe --tags --always)"
+	COMMIT_DATE=$(${GIT} log --max-count=1 --pretty="${COMMIT_DATE_FORMAT}" HEAD)
+	[ -z "$(git diff-index --name-only HEAD)" ] || FLAG="${FLAG_DIRTY_VALUE}"
+      fi
     fi
-    VN="$VN$FLAG"
-    [ -z "$VN" ] && VN="$NO_VERSION"
+  else
+    echo "Warning: git repository not found in current directory (see GIT_DIR in git documentation)." >&2
+  fi
+  VN="${VN}${FLAG}"
+  [ -z "${VN}" ] && VN="${NO_VERSION}"
 else
-    VN=$(getFileConfig "VERSION" "$NO_VERSION")
-    COMMIT_DATE=$(getFileConfig "COMMIT_DATE" "$NO_COMMIT_DATE")
+  VN=$(getFileConfig "VERSION" "${NO_VERSION}")
+  COMMIT_DATE=$(getFileConfig "COMMIT_DATE" "${NO_COMMIT_DATE}")
 fi
 
-if [ "$CREATE_FILE" = "true" ]; then
-    if [ -n "$FILE" ]; then
-	FILE_OR_PROJECT="file '${FILE#$MAIN_DIR/}'"
-    else
-	FILE_OR_PROJECT="project"
-	if [ -f "$VERSION_FILE" ]; then
-	    LIB_CURRENT=$(getFileConfig "LIB_CURRENT")
-	    LIB_REVISION=$(getFileConfig "LIB_REVISION")
-	    LIB_AGE=$(getFileConfig "LIB_AGE")
-	    LIB_VERSION=$(getFileConfig "LIB_VERSION" "")
-	fi
+if [ "${CREATE_FILE}" = "true" ]; then
+  if [ -n "${FILE}" ]; then
+    FILE_OR_PROJECT="file '${FILE#${MAIN_DIR}/}'"
+  else
+    FILE_OR_PROJECT="project"
+    if [ -f "${VERSION_FILE}" ]; then
+      LIB_CURRENT=$(getFileConfig "LIB_CURRENT")
+      LIB_REVISION=$(getFileConfig "LIB_REVISION")
+      LIB_AGE=$(getFileConfig "LIB_AGE")
+      LIB_VERSION=$(getFileConfig "LIB_VERSION" "")
     fi
-    cat <<EOF > "${VERSION_FILE}.new"
-# Generated by $PROG_NAME
+  fi
+  cat <<EOF > "${VERSION_FILE}.new"
+# Generated by ${PROG_NAME}
 # Date: $(date --rfc-2822)
 
-# Version of the $FILE_OR_PROJECT
-VERSION: $VN
+# Version of the ${FILE_OR_PROJECT}
+VERSION: ${VN}
 
-# Commit date of the $FILE_OR_PROJECT
-COMMIT_DATE: $COMMIT_DATE
+# Commit date of the ${FILE_OR_PROJECT}
+COMMIT_DATE: ${COMMIT_DATE}
 
 EOF
 
-    if [ -n "$LIB_VERSION" ]; then
-	cat <<EOF >> "${VERSION_FILE}.new"
+  if [ -n "${LIB_VERSION}" ]; then
+    cat <<EOF >> "${VERSION_FILE}.new"
 # Most recent interface number that the main library implements.
-LIB_CURRENT: $LIB_CURRENT
+LIB_CURRENT: ${LIB_CURRENT}
 
 # Implementation number of the current interface the main library implements.
-LIB_REVISION: $LIB_REVISION
+LIB_REVISION: ${LIB_REVISION}
 
 # Difference between the newest and oldest interfaces that the main library implements.
-LIB_AGE: $LIB_AGE
+LIB_AGE: ${LIB_AGE}
 
 # Main library version number according to the libtool policy.
-LIB_VERSION: $LIB_VERSION
+LIB_VERSION: ${LIB_VERSION}
 EOF
-    fi
-    if ! test -f "${VERSION_FILE}" || ! diff -I "^#" -q "${VERSION_FILE}" "${VERSION_FILE}.new" > /dev/null; then
-        mv "${VERSION_FILE}.new" "${VERSION_FILE}"
-    else
-    	rm -f "${VERSION_FILE}.new"
-    fi
+  fi
+  if ! test -f "${VERSION_FILE}" || ! diff -I "^#" -q "${VERSION_FILE}" "${VERSION_FILE}.new" > /dev/null; then
+    mv "${VERSION_FILE}.new" "${VERSION_FILE}"
+  else
+    rm -f "${VERSION_FILE}.new"
+  fi
 fi
 
-[ "$TIMESTAMP" = "true" ] && VN="$VN ($COMMIT_DATE)"
+[ "${TIMESTAMP}" = "true" ] && VN="${VN} (${COMMIT_DATE})"
 
-echo $VN
+echo ${VN}
 
 exit 0
